# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

modules-search: [ local ]

instances:
- id:       kms
  module:   shellprocess
  config:   shellprocess_kms.conf
- id:       autologin
  module:   contextualprocess
  config:   contextualprocess_autologin.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - summary
- exec: []
- show:
  - finished

branding: arcade
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
