---
defaultGroups:
  - users
  - lp
  - video
  - network
  - storage
  - wheel
  - audio
  - optical
  - scanner

autologinGroup:  autologin
sudoersGroup:    wheel
setRootPassword: true
doAutologin:     false
passwordRequirements:
  minLength:     6
  maxLength:     -1
userShell:       /bin/zsh
