---
showSupportUrl:        true
showKnownIssuesUrl:    false
showReleaseNotesUrl:   false
showDonateUrl:         false
requirements:
  requiredStorage:     8
  requiredRam:         1.0
  internetCheckUrl:    "https://google.com"
  check:
    - storage
    - ram
    - power
    - internet
  required:
    - storage
    - ram
